// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "amelagustina",
    "email": "amelagus123@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

### Dapatkan semua pengguna
// get All Users
GET http://localhost:5000/users

### Dapatkan satu pengguna
// GET Single User
GET http://localhost:5000/users/a05ce404-6618-4438-a367-b9ba22e14975

### Perbarui pengguna
// Update A User
PATCH http://localhost:5000/users/48cee5c8-1f10-4949-b4f4-f27279e8a54f
Content-Type: application/json

{
    "name": "Amel Updated",
    "email": "amelagus@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

### Hapus Pengguna
// Delete A User
DELETE  http://localhost:5000/users/22bc1ce1-8a8f-4a25-9bed-341db5a66fb9

### Masuk sebagai pengguna
// login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "name": "amelagustina",
    "email": "amelagus123@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

### Dapatkan info pengguna yang saat ini masuk
GET  http://localhost:5000/me

### Keluar dari akun pengguna yang saat ini masuk
// logout
DELETE  http://localhost:5000/logout

### Dapatkan SEMUA PRODUK
// GET ALL PRODUCTS
GET http://localhost:5000/products

### Dapatkan SATU PRODUK
// GET SINGLE PRODUCT
GET http://localhost:5000/products/faaad4f0-925a-491e-bd3f-3e8d36c5983

### POST DATA PRODUK
// POST DATA PRODUCT
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "isauraputra",
    "price": 95000
}

### Perbarui DATA PRODUK
// UPDATE DATA PRODUCT
PATCH  http://localhost:5000/products/2bf45a6c-3d32-4eb2-a544-67e15b78bb69
Content-Type: application/json

{
    "name": "isaura Updated",
    "price": 56000
}

### Hapus PRODUK
DELETE  http://localhost:5000/products/dbdaee68-b7e8-4046-b54b-90ca1f2adcdc

###
// Image url
POST http://localhost:5000/products
Content-Type: application/json

{
  "name": "Isaura updated",
  "price": 75000,
  "imageUrl": "http://example.com/image.jpg"
}

### Membuat Produk dengan Payment Status
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "celer",
    "price": 450000,
    "imageUrl": "http://example.com/image.jpg",
    "userId": 6,
    "payment_status": "menunggu konfirmasi"
}

### Memperbarui Payment Status Produk
PATCH http://localhost:5000/products/8da17575-8003-483c-8e55-a4f53073b112
Content-Type: application/json

{
    "payment_status": "selesai"
}
